### ISSUE TITLE
Does this API still work?

### ISSUE THREAD

**Issue by jaraco** [wodim/freedompop-telegram#4]
I'm trying to use this API to perform a simple operation. I get as far as being issued an access token, but when I use that access token to _register_push_token or action_get_usage (bypassing _register_push_token), I get a `401 Client Error: Unauthorized for URL`. I do see the access token being transmitted in the request.

Have you used this library recently or can you to confirm it still works?

**Comment by wodim** [comment]
I don't know, I guess it does not. I haven't used in a long time, and I 
no longer own a FreedomPop card.

**Comment by jaraco** [comment]
It's possible it still works for older accounts. When I signed up for FreedomPop only a few weeks ago, they set up my account in a `beta` site, so they may be moving accounts to a new infrastructure and only supporting the old API for older accounts.

Can you share some details about how you developed this client on an undocumented API? Perhaps I could replicate some of your work with my account and develop a revised client that works with my newer account.

**Comment by wodim** [comment]
I disassembled the Android app using apktool and looked at the resulting code, there was a certain file that contained all API endpoints. I don't know if the current app is laid out like that.

Another option is to do a man-in-the-middle attack with something like Fiddler. That will work unless the app uses certificate pinning.

**Comment by jaraco** [comment]
Thanks for the advice. I'll let you know if I find anything.

**Comment by jaraco** [comment]
I got it working. Turns out the User-Agent header is important. Based on your work, I've put together a [general-purpose client library](https://github.com/jaraco/freedompop). If there's interest, I'd be happy to extend the API so it's a drop-in replacement for the client used in this telegram bot project.

**Comment by wodim** [comment]
Personally I have no interest, as I no longer have a SIM card from them.
